W-14775713 | Java 17 runtime compatibility changes release
mulesoft/mule-json-module pull request #207
Opened 2024-03-19 08:48 UTC by alexandru-babei-softvision

Reflection usage in JSON module with regards to the JSON Tools library was needed before in order to access the private class members involved in working around the thread leak issue.

Since we wanted to avoid breaking backwards compatibility, which could have involved either replacing the library or deprecating the schema versions supported by the library, we had to come up with several proposals for changing how the library behaves without impacting the rest of the functionality.

We came up with a creative solution, which we also described in a [tech spec](https://docs.google.com/document/d/1Ub0ZELgbPgSzsVF7XdeL9hRhHa0SoZDxhmxWUFncwgU/edit#heading=h.gbqonn3wmdgy), where we modify the library classes at compile time during shading, making the class members that we need to change as public and non-final, right before the shader performs package relocation.

You can also see this behaviour being tested in [JsonToolsReflectiveAccessTestCase.xml](https://github.com/mulesoft/mule-json-module/blob/feature/jdk-17-validation/src/test/munit/JsonToolsReflectiveAccessTestCase.xml) where we load the shaded classes and make sure that the class members are public.

The reflective access test case plays an important role in making sure that the custom shader is always invoked during compilation and that the class members are compatible with the reflective access performed at runtime.

2024-03-19 18:28 UTC, elcoya approved these changes

2024-03-19 18:31 UTC, elcoya requested changes
Wait a sec... a new minor version should be coming out from the master branch, not support. You would create the support branch by merging the code into master. This PR should go into master... `support/2.5.x` would only start existing once you release this minor. (the pipeline will actually do that work).

2024-03-19 18:46 UTC, elcoya approved these changes, later dismissed

2024-03-20 02:44 UTC, acurci-at-mulesoft submitted a review, later dismissed

2024-03-20 09:39 UTC, alexandru-babei-softvision commented
The target branch was changed to `main`. At this point in time, both the support and the main branches have the same commit history. Let's hope that the release pipelines won't have an issue performing the release when the support branch already exists.

2024-03-20 13:43 UTC, acurci-at-mulesoft submitted a review, later dismissed

2024-03-20 14:30 UTC, aiannucci requested changes
Do this release from support/2.5.x

2024-03-20 14:40 UTC, elcoya approved these changes

2024-03-20 14:40 UTC, aiannucci approved these changes

2024-03-20 14:45 UTC, alexandru-babei-softvision commented
We've changed the target of the PR back to the support branch, which basically means that we'll going to be performing the release using the alternative method of using the support branch and then manually updating the version on the main branch to the next minor snapshot version.

Thanks to everyone who helped out.

2024-03-20 16:00 UTC, merged